name: CI

on: [push, pull_request, workflow_dispatch]

jobs:
  spelling:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Check spelling
      uses: crate-ci/typos@master

  pyright:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Checkout stubs
      uses: actions/checkout@v4
      with:
        repository: bl-sdk/pyunrealsdk
        path: pyunrealsdk
        sparse-checkout: |
          stubs

    - name: Add stubs to pyproject
      run: sed -i 's/# CI ADD STUB PATH HERE/stubPath = "pyunrealsdk\/stubs"\nreportMissingModuleSource = false/' pyproject.toml

    - name: Run pyright
      uses: jakebailey/pyright-action@v2

  ruff:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Run Ruff Linting
      uses: chartboost/ruff-action@v1

    - name: Run Ruff Formatting
      uses: chartboost/ruff-action@v1
      with:
        args: format --check
